apiVersion: ENC[AES256_GCM,data:Yno=,iv:RJlms8eTGlmvxGieVHry5Ax/atR6kDjKtJix/s9d9+4=,tag:3h/DBUMHbDm4jfQh1PDI3w==,type:str]
kind: ENC[AES256_GCM,data:g6ngYJWt,iv:JfjNe6LLfOyjUIIvCi74YOEjtJTZEPL+nU77PR3QKnk=,tag:y2R0YQzMg+qYsq8FGvUGWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eBZnhnBtrW5F2nO+FOvx,iv:91eopHhPLXqEFbd7w8T0CTW5mlt61+aSE9DjF6NLmCQ=,tag:6mUfpo05O8BMMsOwSrvM+g==,type:str]
    namespace: ENC[AES256_GCM,data:rygXSf2eOA==,iv:sv1EbvxNhWFJiXH3CIqWWsj0AyyVQKprCjYS6mcYrEY=,tag:GamxP27/KvfST1pRfdNx+A==,type:str]
type: ENC[AES256_GCM,data:JtNO5EQ/,iv:kWjZW52pyyMmSQuV06P33W7E7/qCN1NShQZ3BZ3+d/I=,tag:M+1wtEo3qA48seDkPpwiUw==,type:str]
stringData:
    DB_HOST: ENC[AES256_GCM,data:4ol2V5HRw7Bf11Nf1HCDg0JAZ7ylrbktkAYz7CMX3ONb0GWpGTqzvdX1Q/BmCza9w64kGa3Sa6Kz000=,iv:uQyq4BI5gkRwMc4+jDsKfj3ZRPtLDriCO9PASxd1Kr4=,tag:LoueIXYjBqrkmp8/LO+moA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:TFhFQQ==,iv:h+4/O35f9bOmavfwnneKwNl1320U2vbCC696FzmM4uA=,tag:J83Rc3Ri7liD8+zw1RtgcQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:cYzbFfnkhafV6cAd,iv:/8APPwx7xn0dVDjeQ4X6U6NolD6Q6mLLgf4/3L9IwSc=,tag:/Cw8YSdCa2mj6rw+z0WYwA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:UHlOQM+YjnkBCo5WUUX6fQ==,iv:rwQO6Zt55UnHYdfIm5qt3wuc6HK4uL+CQ4rW5XJVucg=,tag:9MApJLGhDav43gXmjl6unQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:BUltr4wp,iv:xHy0iaRw+niarhigoK9kJIyhuJswLI7rrueWwQth/t8=,tag:bj1zQwCiVU05th3TWOOwdw==,type:str]
    DB_SSLMODE: ENC[AES256_GCM,data:HTG1Rh01jg==,iv:Mlk9B1bxbBCnUD53dec2qKoTt4cRAuEFaoHl7al36TY=,tag:wBJKT5JGSoKcmzlrJSa5wg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:SG0S/yiVKVhkZQJ0/F8Qg11jy6Pj4k0a+jcDjDPZ3z5kTNudj8Qu+eGeSTY2DbwL6WAbUOGTZA2UddDHOc9kkw==,iv:JwFq6RLMtOvRoDFyx3cAvTr+9FzNmJvOtlNaD71gk7c=,tag:WRug7XuL55eSt3OTgs7IIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1stadct7wyau4rk6tkamkc0apwgqgqkfadkypjspvxv3wjn6q2qls9fwtr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNanNxSk12djQ1czFld3lp
            cVF0QkFBVFdiajBFSFg1QjZnbjRDdW5idUQ0ClZwbmdMRHkzU21KY0FIbzFGaFVB
            UDlzQ0NmUm9NTGR5MmlZcTdIRXZFUG8KLS0tIDNic2ZHK3JlaWFkdDFvQ1hJWThK
            Mk1RcDVINmF6SmZBckNHYlRmbmM0LzAKHk/eeFO6PDAY9V5FBDyd7DGPvC/bvePu
            O63KBhpttnVyvAQ7y6a/nPEhLmlqhEIARRG1yhPIP1LfXJuaMKaUoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T08:59:31Z"
    mac: ENC[AES256_GCM,data:w3K5rKIPZCArlJOaZp6J0jNrYlnUqJS4Vgbt7gCPthuF4Gqq2C+jVNESPDi0YOZ6BETUeC1wSCRZU2ckIOeyp54s0IAnsjCifUzW6JO7IPaO3HdK6MyI64lFx5E4SulNJag98gXwyBTsDsH4dTmuQNfgBZ2Pz9y/f3XtEYg8Vk0=,iv:wpZcGnG3t+eY8/FQPcCtYvod1lAr6WEANgRzvODHfkc=,tag:SBN64NqB6/eCnWRbgA1qAg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
