apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sub2api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hbf-ink/sub2api.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sub2api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
