apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sub2api

resources:
  - deployment.yaml
  - ingress.yaml

images:
  - name: ghcr.io/hbf-ink/sub2api
    newTag: v0.2.0  # 更新版本时修改这里
