apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sub2api

resources:
  - deployment.yaml
  - deployment-beta.yaml
  - ingress.yaml

images:
  - name: ghcr.io/hbf-ink/sub2api
    newTag: v0.2.0  # 生产版本
  - name: ghcr.io/hbf-ink/sub2api
    newName: ghcr.io/hbf-ink/sub2api
    newTag: beta    # Beta 版本
