all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
  children:
    ops:
      hosts:
        ops-tokyo-01:
          ansible_host: 43.163.210.42
          ansible_password: y#AV(ZjOHNp0}9u>G7
          node_role: ops
          wireguard_ip: 10.10.0.1
    prod:
      hosts: {}
