r2:
    endpoint: ENC[AES256_GCM,data:AOZ6UN+D6twhzbpa6+eD16I7XoJurqM5TJzvgHvwORqP48d4FHvHLgoYLE6B7zCYRSiTosFtdbX573hlUzj75Ec=,iv:hZZfs6oK+boe8hNad1lzdaURgkTv0Uu8HH9CcG6zUNc=,tag:sKxLsmX9clgdlwXUSj9WcQ==,type:str]
    access_key_id: ENC[AES256_GCM,data:3r0g7i13sWpNRXwNc5PD8alrFfYovpufJ7so7lzC36c=,iv:UuUyn2tS+r9+7qzGYS1AcMsdjp0i1qfjWZZsLjPuKng=,tag:27Fey3NwL6JiYI/ZKyl9VA==,type:str]
    secret_access_key: ENC[AES256_GCM,data:BsayyJqGrHLXunRZVHzUU7YkWKRRywxvMWHcDwks+Qt+3TnknoPpEPNeQAxqCY8iq0ywsPyilvFbbJVOjEQqUQ==,iv:fC1tEvd+6gYU05WrXGIkEK5v4JWK/Ydqv14N3JX/pxs=,tag:4JjlGSXcxj8NrGzZ6+yZgQ==,type:str]
    bucket: ENC[AES256_GCM,data:0d/wtA2tfMVfgw==,iv:XPQhr0chd+QHAIN5qLvIwJyMzqK5Ffa/Koqvy1vxt8U=,tag:op12oU5Qf3EB2+gQ0aMBEQ==,type:str]
ops:
    lldap_admin_password: ENC[AES256_GCM,data:xYaIhTHfEUsYVbe4hQ==,iv:5Hlqb8PWf0DCInwesw+BxPFY7TjUU98PwgHHBOrVRpk=,tag:pBPfsYt9XRBdh1pav+Q7HA==,type:str]
    lldap_jwt_secret: ENC[AES256_GCM,data:WBqGFLDQZOexFlmtPYswmoJSQcCZ4Y9ujOi6jtSxtfwcdS4nfYONJg==,iv:+I7epl+MeJFGBXuFPBWHDWuhALKaddMrq4qZe8ghAMM=,tag:G/EvayUNpClSXgS1RSd3zQ==,type:str]
    authelia_jwt_secret: ENC[AES256_GCM,data:WX/ukFgD9WWGEDBpK+jM9S4ACKv6XVRdAX/lZRsK16UyA0gqv7JSRL04iLQ=,iv:zYd8Tgay0ekA+02OCv42HaB+xQ7DVaaKxK9NM87WOu0=,tag:zV1fRDvH52fR2BAakC/uMA==,type:str]
    authelia_session_secret: ENC[AES256_GCM,data:I6HX793EyFd1V6n11Zu1lMwACEe1BvUzZ9ljfZ36znNkzg27pTez/g==,iv:nu1ODlRO1DZJMgXB9IhhkGl22u4S7umT4Ee7vbyI6cs=,tag:CSy0ZB8ADAcXDiw8DqUOhw==,type:str]
    authelia_storage_key: ENC[AES256_GCM,data:wqtm4iHAfm3VpsQdJW6V+P4lyu43+98QjdaQhSDklnt4g4I2qyGbQevL,iv:VfNebNxVYkDp2Mp65YChciCNrY8t9CnW+UpXhCMBWoU=,tag:1CbgRVD9syYSsfUhxcf9qg==,type:str]
    homarr_secret_key: ENC[AES256_GCM,data:ER5WBZhr2OYwwJo4XaSFuOmEJnTv2UG79A71oygTw1gvWwgVWQJqmD17iu8yYZ/ZTslMSlRjsOfsCNYokNBuIA==,iv:AJzMr0eupttcvarASRTWsNHVNkX1kr3kbCK0hDiySW4=,tag:gtm37Gw7XZN0VyovJ8RW9Q==,type:str]
    homarr_auth_secret: ENC[AES256_GCM,data:YgaYzrDP8qZi+d9Wd14msDBs3Ssq3ssmqvm/DuzLUkS+VWo68Xm3GE0zxOuJZBFD+Xjpdt5UzbLafev87eXMQQ==,iv:sArEu/iBoz/quRD/eu0KW6mdF1RdVOFOlcn/byw7O0g=,tag:ZwX48V35cn/YZoyTI+wlsw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINKMD8lPcHsMv/SBryWWUOtOSDdn/n3qmxrjqDLPf0CJ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFlPY3dMdyBqZ0VW
            N2dKL0p2NXhqMXFPNkZ6Z29ucUpkTCtQOEgwYXIzM08yaVgxZUY0Ck9rblhtZ0pj
            Q0R4Q3dONFlxV1A5YVhjemRVWGxQa0JLY2ZDVWhDMitzOTAKLS0tIEJzSzd6NWVz
            dVJDYnNZN0FpeDluYWRMbVVKeGd4MW9zTHoydkFVV2x3NTgK3caXKKsl1qDLVu2V
            mMaxnXBJHmCiGlNcHP9MU3EX/6c5wpHLhoPrM91GFZ3nHGmqgXZdSBlZ+sKrw17k
            AAfpWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T11:00:23Z"
    mac: ENC[AES256_GCM,data:X/8RDABssBg82B8gsvNaGbBC9GFqrL2uz9I9W/WUgA7v7zioSDN8ztpKHs1QF0ScxAmE91sl+YWY584wuvrUXxG6ZGHbn5yHdVkPfLqK+w0W+ko94YmUdNKb/ePtz50e6UZXhyCwREcaN5S7rt+dTgKNN20CKae7VBztoFuwPAA=,iv:odEU+rIyV/h5fyItN299+1DXxvSboiKncpzmSIyAjc4=,tag:g7G9LI/bU4Qa0058AAN/wQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
