r2:
    endpoint: ENC[AES256_GCM,data:KcuCWW2Gy0MvCuhX16z5PUg3bNYbP7nhxqvnf7jUMTan4SBn9J9c5Iqbfc3cQiRRyvtK0iH29LWi1pY9XNhrSb4=,iv:HQGA3MUnvLYRwexCuWKIEwK/N25oe80R9/OLR61woxk=,tag:u3wfioC4MTbAO5KNGbegwA==,type:str]
    access_key_id: ENC[AES256_GCM,data:ISrqEeLvHPjQrbfz9WecgdKa5KI9NvAKGdb5jnPH7/E=,iv:j/Zd8mDCaH2VnYOOK5/ce1so74j8UBbIldhB2uLHQyk=,tag:FKNpT6d7+5/6DJ+RLOfLzg==,type:str]
    secret_access_key: ENC[AES256_GCM,data:IcQTG2dzP8Z1cdJmd2ynqy4S/boX7dbWcouEwsmMUpKmyoqh7cFHtz2FfG4vo2KUbWfCZkvY3NFIDrDwm2SgQQ==,iv:t8TXoEaaQb7khK5VTofEV82/9R0CmzhPxP2v3J8tHZE=,tag:H18IXT/4aVLP238nkzH6FQ==,type:str]
    bucket: ENC[AES256_GCM,data:6qkDGPPIAvYygw==,iv:Zxt30UtIBhxdCHAZZ7Q8dkhOHd7R5hZVQ6iSCMXtw5A=,tag:3gIccH2hLET9/gHPYUFcEA==,type:str]
ops:
    lldap_admin_password: ENC[AES256_GCM,data:B/Ru2lX2BHR5Vo1NAQ==,iv:pcZjmC0bWBXeV81Uxwut8yxR6KtXkRW1A6lEREo3nvc=,tag:4q80DyLuvvVVBmNRXNfQ/w==,type:str]
    lldap_jwt_secret: ENC[AES256_GCM,data:GjxwzSLLJRToLd94WM3FbB6ddrC8vjfZbdbvPdqWQ1CNvJ1XtEt3+z0UjQ==,iv:Q8TbRLGTOX/FuUZ+WOlEyTpUaKZYKmlrqQ1BTa4jFRQ=,tag:uUvv/86FLMW5kaxgWhvurg==,type:str]
    authelia_jwt_secret: ENC[AES256_GCM,data:wKRIKDnnzR2LYTzI0fFzeQiLVKXdaFgYNEXaXHePaLmvQlTFMptDhoItvfvXO5Y13A==,iv:fa3Dep8VmSK2tXpxG8fCGBlYzqMHw+DxXsfCUAzjbjU=,tag:JsCUO0q4F1YnpGmoJy6Nig==,type:str]
    authelia_session_secret: ENC[AES256_GCM,data:78GnAKBhqj/YiVKjRWlny0tvxlsiSuW/ZpSj0WgEsoh+DKwcWsHJi4ipfQ==,iv:JrfcngovqZhJqdmRCulT3McPDPqnoRjSQkTfsPt5sVI=,tag:Tha2kZdOOHZobNt5N5b5Jg==,type:str]
    authelia_storage_key: ENC[AES256_GCM,data:WvqyiOCCMvU/OrJfs0pNRdoEldSTR9qnU2lYarcZnc505paP5DVcsyOWYH4=,iv:+HMsp02rU8t0BBxNC4aLsZsrl4PTEik1+IRtSH+peqA=,tag:h1CLxfB3Mup6GTvv9qRaKw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINKMD8lPcHsMv/SBryWWUOtOSDdn/n3qmxrjqDLPf0CJ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFlPY3dMdyBXNmRL
            RGMwZy80NWhISzZoWDQyNXludXlFQStwL3NZOEIwK1BVRnBzSFNnCjUzVjlSV3NN
            SUZZNjQrU1FpVm54a1NTb2NrbmxnWVNUbUJrS2gvc3ZJVTAKLS0tIGdGeUdySS9M
            NTBvNWxMOHNBVy8rRE83VFE3QXdlaG8zajlsNG42MjlQYlEKb6mzXMxSnOup9hyR
            gfM1Gj3tuZcbe0g6LRUa7qsSrvc5I0JUUmASfEIahMO3G8XS4hKCDydOQdwFLOnf
            ptcXMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T09:11:30Z"
    mac: ENC[AES256_GCM,data:9IqNFNRPL2kg2YaAR4F8OlT577A9d/t7ESwGrFzSJl/UAYHusU0tBdqofxk3E5cy2KIjflwuKgk6NOfuGx/aNpZ1jLW3cMhTiAc+KI/Gw+yfOj41Vn/KL2JoJ3shXwicSJvQlCVau9DApvH8y8CqlmRm5VQYHPec6rvdwkXWUlY=,iv:tJLJxr6m2ry9pbgpnldwUR/WI8t5dkiMHRL634Ud9Cg=,tag:e2tfjQzb3/ngyGJI9iRAXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
